# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 543)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 40, 931, 81))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 210, 521, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create_testButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.create_testButton.setObjectName("create_testButton")
        self.horizontalLayout.addWidget(self.create_testButton)
        self.starting_testButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.starting_testButton.setObjectName("starting_testButton")
        self.horizontalLayout.addWidget(self.starting_testButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.interpreter_result_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.interpreter_result_button.setObjectName("interpreter_result_button")
        self.verticalLayout.addWidget(self.interpreter_result_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MapTest"))
        self.label.setText(_translate("MainWindow", "Добро-пожаловать в тестирующую систему map test"))
        self.create_testButton.setText(_translate("MainWindow", "Создать тест"))
        self.starting_testButton.setText(_translate("MainWindow", "Начать тестирование"))
        self.interpreter_result_button.setText(_translate("MainWindow", "Интерпретировать результаты"))
