# Form implementation generated from reading ui file 'question_ui_input_answer1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from files.testing_system_files.test_image_label import TestImageLabel

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1084, 624)
        Form.setMinimumSize(QtCore.QSize(650, 400))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setKerning(False)
        Form.setFont(font)
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 10, 1071, 751))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1069, 749))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 510, 381, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.answers_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.answers_layout.setContentsMargins(0, 0, 0, 0)
        self.answers_layout.setObjectName("answers_layout")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.answers_layout.addWidget(self.label_2)
        self.answer_line_edit = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        self.answer_line_edit.setObjectName("answer_line_edit")
        self.answers_layout.addWidget(self.answer_line_edit)
        self.image_label = TestImageLabel(parent=self.scrollAreaWidgetContents)
        self.image_label.setGeometry(QtCore.QRect(430, 10, 551, 521))
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.question_plain_text = QtWidgets.QPlainTextEdit(parent=self.scrollAreaWidgetContents)
        self.question_plain_text.setGeometry(QtCore.QRect(10, 10, 379, 471))
        self.question_plain_text.setObjectName("question_plain_text")
        self.save_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.save_button.setGeometry(QtCore.QRect(10, 550, 209, 23))
        self.save_button.setObjectName("save_button")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Вопрос с вводом ответа"))
        self.label_2.setText(_translate("Form", "Введите ответ:"))
        self.save_button.setText(_translate("Form", "Сохранить"))
