# Form implementation generated from reading ui file 'question_ui_choice_answer1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from files.testing_system_files.test_image_label import TestImageLabel


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1324, 652)
        self.question_plain_text = QtWidgets.QPlainTextEdit(parent=Form)
        self.question_plain_text.setGeometry(QtCore.QRect(10, 10, 671, 131))
        self.question_plain_text.setObjectName("question_plain_text")
        self.image_label = TestImageLabel(parent=Form)
        self.image_label.setGeometry(QtCore.QRect(690, 10, 611, 541))
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.save_button = QtWidgets.QPushButton(parent=Form)
        self.save_button.setGeometry(QtCore.QRect(30, 590, 209, 23))
        self.save_button.setObjectName("save_button")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 160, 671, 391))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.checkbox_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.checkbox_layout.setContentsMargins(0, 0, 0, 0)
        self.checkbox_layout.setObjectName("checkbox_layout")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Вопрос с выбором ответа"))
        self.save_button.setText(_translate("Form", "Сохранить"))


