# Form implementation generated from reading ui file 'question_ui_open_answer1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from files.testing_system_files.test_image_label import TestImageLabel


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1202, 692)
        Form.setMinimumSize(QtCore.QSize(1000, 600))
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1171, 661))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1169, 659))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.answer_plain_text = QtWidgets.QPlainTextEdit(parent=self.scrollAreaWidgetContents)
        self.answer_plain_text.setGeometry(QtCore.QRect(30, 220, 411, 371))
        self.answer_plain_text.setObjectName("answer_plain_text")
        self.image_label = TestImageLabel(parent=self.scrollAreaWidgetContents)
        self.image_label.setGeometry(QtCore.QRect(490, 220, 641, 371))
        self.image_label.setObjectName("image_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(940, 620, 211, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.question_plain_text = QtWidgets.QPlainTextEdit(parent=self.scrollAreaWidgetContents)
        self.question_plain_text.setGeometry(QtCore.QRect(30, 10, 1091, 161))
        self.question_plain_text.setObjectName("question_plain_text")
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(30, 190, 91, 16))
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Развернутый вопрос"))
        self.image_label.setText(_translate("Form", "Нажмите, чтобы добавить картинку"))
        self.save_button.setText(_translate("Form", "Сохранить"))
        self.label.setText(_translate("Form", "Ваш ответ:"))
