# Form implementation generated from reading ui file 'choosing_maket_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(289, 135)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 90, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.paramSelect_maket = QtWidgets.QComboBox(parent=Dialog)
        self.paramSelect_maket.setGeometry(QtCore.QRect(10, 50, 251, 22))
        self.paramSelect_maket.setObjectName("paramSelect_maket")
        self.paramSelect_maket.addItem("")
        self.paramSelect_maket.addItem("")
        self.paramSelect_maket.addItem("")
        self.visual_choose_maket = QtWidgets.QLabel(parent=Dialog)
        self.visual_choose_maket.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.visual_choose_maket.setObjectName("visual_choose_maket")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Выбор макета"))
        self.paramSelect_maket.setItemText(0, _translate("Dialog", "Развернутый ответ (проверяется вручную)"))
        self.paramSelect_maket.setItemText(1, _translate("Dialog", "Запись ответа"))
        self.paramSelect_maket.setItemText(2, _translate("Dialog", "Выбор варианта(ов) ответа(ов)"))
        self.visual_choose_maket.setText(_translate("Dialog", "Выберите макет"))


class ChoosingMaketWindow(QDialog, Ui_Dialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

        # Атрибут для хранения выбранного макета
        self.selected_maket = None

        # Привязка кнопок Ok и Cancel
        self.buttonBox.accepted.connect(self.accept_selection)
        self.buttonBox.rejected.connect(self.reject_selection)

    def accept_selection(self):
        """Сохраняет выбор пользователя при нажатии Ok и закрывает окно."""
        self.selected_maket = self.paramSelect_maket.currentText()  # Сохраняем выбранный макет
        self.accept()  # Закрываем окно и возвращаем код accept

    def reject_selection(self):
        """Закрывает окно без сохранения выбора."""
        self.reject()  # Закрываем окно и возвращаем код reject
