# Form implementation generated from reading ui file 'question_ui_maket_choice_answer1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from files.creator_files.image_label import ImageLabel
from PyQt6 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1346, 547)
        self.input_question_label = QtWidgets.QLabel(parent=Form)
        self.input_question_label.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.input_question_label.setObjectName("input_question_label")
        self.question_plain_text = QtWidgets.QPlainTextEdit(parent=Form)
        self.question_plain_text.setGeometry(QtCore.QRect(10, 40, 201, 341))
        self.question_plain_text.setObjectName("question_plain_text")
        self.variant_list_view = QtWidgets.QListView(parent=Form)
        self.variant_list_view.setGeometry(QtCore.QRect(220, 40, 451, 341))
        self.variant_list_view.setObjectName("variant_list_view")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 510, 211, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choosing_maket_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.choosing_maket_button.setObjectName("choosing_maket_button")
        self.horizontalLayout.addWidget(self.choosing_maket_button)
        self.save_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.answer_plain_text = QtWidgets.QPlainTextEdit(parent=Form)
        self.answer_plain_text.setGeometry(QtCore.QRect(140, 390, 531, 71))
        self.answer_plain_text.setObjectName("answer_plain_text")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 390, 121, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_variant_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.add_variant_button.setObjectName("add_variant_button")
        self.verticalLayout.addWidget(self.add_variant_button)
        self.is_right_check_box = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.is_right_check_box.setObjectName("is_right_check_box")
        self.verticalLayout.addWidget(self.is_right_check_box)
        self.image_label = ImageLabel(parent=Form)
        self.image_label.setGeometry(QtCore.QRect(690, 20, 641, 481))
        self.image_label.setObjectName("image_label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(400, 470, 271, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.value_spinbox = QtWidgets.QSpinBox(parent=self.horizontalLayoutWidget_2)
        self.value_spinbox.setObjectName("value_spinbox")
        self.horizontalLayout_2.addWidget(self.value_spinbox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Вопрос с выбором ответа"))
        self.input_question_label.setText(_translate("Form", "Введите вопрос:"))
        self.choosing_maket_button.setText(_translate("Form", "Изменить макет"))
        self.save_button.setText(_translate("Form", "Сохранить"))
        self.add_variant_button.setText(_translate("Form", "Добавить ответ"))
        self.is_right_check_box.setText(_translate("Form", "Правильный ответ"))
        self.image_label.setText(_translate("Form", "Нажмите, чтобы добавить картику"))
        self.label.setText(_translate("Form", "Относительная ценность вопроса"))
