# Form implementation generated from reading ui file 'question_ui_maket_open_answer1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from files.creator_files.image_label import ImageLabel


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1077, 600)
        Form.setMinimumSize(QtCore.QSize(1000, 600))
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 1061, 581))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1059, 579))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 31))
        self.label.setObjectName("label")
        self.question_plain_text = QtWidgets.QPlainTextEdit(parent=self.scrollAreaWidgetContents)
        self.question_plain_text.setGeometry(QtCore.QRect(140, 20, 391, 491))
        self.question_plain_text.setObjectName("question_plain_text")
        self.image_label = ImageLabel(parent=self.scrollAreaWidgetContents)
        self.image_label.setGeometry(QtCore.QRect(580, 30, 461, 491))
        self.image_label.setObjectName("image_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(840, 540, 211, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choosing_maket_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.choosing_maket_button.setObjectName("choosing_maket_button")
        self.horizontalLayout.addWidget(self.choosing_maket_button)
        self.save_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Вопрос с развернутым ответом"))
        self.label.setText(_translate("Form", "Введите вопрос:"))
        self.image_label.setText(_translate("Form", "Нажмите, чтобы добавить картинку"))
        self.choosing_maket_button.setText(_translate("Form", "Изменить макет"))
        self.save_button.setText(_translate("Form", "Сохранить"))