# Form implementation generated from reading ui file 'input_fio.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QMessageBox
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 570)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 140, 813, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.student_fio = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.student_fio.setObjectName("student_fio")
        self.verticalLayout.addWidget(self.student_fio)
        self.start_test_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.start_test_button.setObjectName("start_test_button")
        self.verticalLayout.addWidget(self.start_test_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1007, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MapTest"))
        self.label.setText(_translate("MainWindow",
                                      "Введите свое ФИО. Пожалуйста, используйте свое настоящее ФИО для последующей идентификации."))
        self.student_fio.setText(_translate("MainWindow", ""))
        self.start_test_button.setText(_translate("MainWindow", "Перейти к тесту"))


class InputFIO(Ui_MainWindow, QMainWindow):
    def __init__(self, parent=None, main_test_window=None):
        super().__init__(parent)
        self.setupUi(self)
        self.main_test_window = main_test_window
        self.start_test_button.clicked.connect(self.start_test)

    def start_test(self):
        if self.student_fio.text():
            self.main_test_window.start_test.emit()
        else:
            QMessageBox(self, title='Поле должно быть заполнено')
